#ip+port
bind    192.168.32.132
port    8888
#persistence
# save    900 1  # 900秒内至少1次修改触发bgsave
# save    300    10
# 开启 AOF
appendonly  yes 
# AOF同步策略：always/everysec/no(暂未实现everysec)
appendfsync no

# 主从复制
# 若配置 slaveof，则当前节点作为从机连接到指定主机
# slaveof 192.168.1.100 8888
# 若未配置，则为 master

